name: CI Pipeline

on:
  push:
    branches: 
      - "master"
      # This will make it run on all branches
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker build -t amitslab/cicd-pipeline:${{ github.sha }} -t amitslab/cicd-pipeline:latest .
    - name: Push to Dockerhub
      run: |
        docker push amitslab/cicd-pipeline:${{ github.sha }}
        docker push amitslab/cicd-pipeline:latest